### ISSUE TITLE
Christmas Lighting Bug

### ISSUE THREAD

**Issue by fruechtegott** [segfault16/modular-led-controller-workstation#128]
Had this bug two times. Can't exactly say what causes this. 
First time was when a working strip setup was connected to a panel. Produced this output.
![christmas_lighting_bug](https://user-images.githubusercontent.com/18394044/67124275-86f39200-f1f2-11e9-939d-36e5dc6caa3f.jpg)
Second time when starting a setup that was not used for about two months. Output was similar to the above.
When in that state the server is accessible but not responding to any changes to the effects.

**Comment by segfault16** [comment]
Also saw this once now, clean install of Pi didn't resolve the issue but blacklisting the audio device did. Adjusted documentation in #132. Let's open a new issue if this re-appears.
