### ISSUE TITLE
Clearing ~/.ledserver or resetting server

### ISSUE THREAD

**Issue by fruechtegott** [segfault16/modular-led-controller-workstation#151]
I had some errors when starting server.py with previous configs.`--no_conf` starts the server fine, but when saving and restarting without `--no_conf` I get the same error again. So overwriting does not work as I would expect. 

I tried manually saving projects with multi-outputs and loading them again, which does not show the virtual devices. But restarting is required for loading the devices.

So for development purposes it would be nice to have a reset command for the terminal which clears ~/.ledserver. Or maybe move the save folder to some other location, so it can be deleted more easily by hand.

Thoughts please.

**Comment by segfault16** [comment]
You can change to a different location for the server configuration with —config_location
