### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by segfault16** [segfault16/modular-led-controller-workstation#83]
I think the project is now more than a 'audio-reactive led strip'.
Maybe we should think about renaming and possibly moving the project.
It's more of a 'Modular LED Controller Workstation' or something.

Suggestions welcome.

**Comment by segfault16** [comment]
@fruechtegott What do you think?

**Comment by fruechtegott** [comment]
Modular LED Controller Workstation aka MOLE COLE Workstation.
Approved!
